### ISSUE TITLE
Issue while sending emojiedittext into http request

### ISSUE THREAD

**Issue by nvavadiya** [ankushsachdeva/emojicon#26] opened 2015-06-12 06:33 UTC
I tried to send emojiconEditText.getText().toString() into http request.Now on another web-service i tried to get those string from the server and display in on EmojiconTextView 

But it show only  "?????" insted of emoji icons..text show perfect but emoji icons not working fine..

**Comment by ankushsachdeva** [comment] 2015-06-12 06:55
Duplicate of #8

**Closed as completed by ankushsachdeva** 2015-06-12 06:55 UTC
